//
//  HybridTools.m
//  testproj-ios-core
//
//  Created by 双虎 on 16/6/2.
//  Copyright © 2016年 Cmptech. All rights reserved.
//

#import "HybridTools.h"
#import "ApiActivityOpen.h"
#import "ApiActivityClose.h"
#import "WebViewUi.h"
#import "NativeUi.h"

@implementation HybridTools

//- (HybridUiBase *) getHybridUiBase:(NSString *)name;

//- (HybridApi *) getHybridApi:(NSString *)name;

+ (HybridUi *) buildHybridUiBase:(NSString *)name{

    //TODO below is generated by tools from config.json:
    
    if ([name isEqualToString:@"WebViewUi"]){
        HybridUi *ui = [[WebViewUi alloc] init];
        return ui;
    }
    if ([name isEqualToString:@"NativeUi"]) {
        HybridUi *ui = [[NativeUi alloc] init];
        return ui;
    }
    
    //TODO throw exception "$name not found"
    return nil;
}

+ (HybridApi *) buildHybridApi:(NSString *)name{
    
    if ([name isEqualToString:@"_app_activity_open"] || [name isEqualToString:@"ApiActivityOpen"]) {
        ApiActivityOpen *api = [[ApiActivityOpen alloc] init];
        return api;
    }
    if ([name isEqualToString:@"_app_activity_close"] || [name isEqualToString:@"ApiActivityClose"]) {
        ApiActivityClose *api = [[ApiActivityClose alloc] init];
        return api;
    }
    
    //TODO throw exception "$name not found"
    return nil;
}


+ (NSDictionary *) getAppConfig:(NSString *)name{
    
    if ([name isEqualToString:@"ApiConf"]) {
        
        //TODO generated by tool (from config.json) later
        return @{@"_app_activity_open":@"ApiActivityOpen", @"_app_activity_close":@"ApiActivityClose"};
    }
    
    //TODO throw exception "$name not found"
    return nil;
}

@end
